version: '3.8'
services:
  ### mongod instances for diagnostic-commands.test.js
  diagnostic-commands:
    image: "mongo:${MONGO_VERSION:-4.2}"
    command:
    - '--replSet'
    - 'replication-test'
    - '--port'
    - '27017'
    ports:
    - "27017:27017"
  ### mongod instances for user-commands.test.js
  user-commands:
    image: "mongo:${MONGO_VERSION:-4.2}"
    command:
    - '--port'
    - '29017'
    ports:
    - "29017:29017"
  ### mongod instances for replication.test.js
  replication-test-0:
    image: "mongo:${MONGO_VERSION:-4.2}"
    command:
    - '--replSet'
    - 'replication-test'
    - '--port'
    - '27000'
    ports:
    - "27000:27000"
  replication-test-1:
    image: "mongo:${MONGO_VERSION:-4.2}"
    command:
    - '--replSet'
    - 'replication-test'
    - '--port'
    - '27001'
    ports:
    - "27001:27001"
  replication-test-2:
    image: "mongo:${MONGO_VERSION:-4.2}"
    command:
    - '--replSet'
    - 'replication-test'
    - '--port'
    - '27002'
    ports:
    - "27002:27002"
