version: '3.8'
services:
  replication-test-0:
    image: mongo:4.0
    command:
    - '--replSet'
    - 'replication-test'
    - '--port'
    - '27000'
    ports:
    - "27000:27000"
  replication-test-1:
    image: mongo:4.0
    command:
    - '--replSet'
    - 'replication-test'
    - '--port'
    - '27001'
    ports:
    - "27001:27001"
  replication-test-2:
    image: mongo:4.0
    command:
    - '--replSet'
    - 'replication-test'
    - '--port'
    - '27002'
    ports:
    - "27002:27002"
