version: '3.8'
services:
  rs-0:
    image: "mongo:${MONGO_VERSION:-4.2}"
    command:
    - '--replSet'
    - 'rs'
    - '--port'
    - '27017'
    ports:
    - "27000:27017"
  rs-1:
    image: "mongo:${MONGO_VERSION:-4.2}"
    command:
    - '--replSet'
    - 'rs'
    - '--port'
    - '27017'
    ports:
    - "27001:27017"
  rs-2:
    image: "mongo:${MONGO_VERSION:-4.2}"
    command:
    - '--replSet'
    - 'rs'
    - '--port'
    - '27017'
    ports:
    - "27002:27017"

  # This will be replaced by
  # hydra replication -r rs-0:27017 -r rs-1:27017 -r rs-2:27017
  mongo-hydra:
    image: "mongo:${MONGO_VERSION:-4.2}"
    command:
    - tail
    - -f
    - /dev/null

  # This will be replaced by
  # hydra replication -r rs-0:27017 -r rs-1:27017 -r rs-2:27017
  app:
    build:
      context: .
    ports:
    - 3000:3000
