---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo
  namespace: default
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongos
spec:
  selector:
    matchLabels:
      # HAS to be equal to the service name
      app: mongos
  serviceName: mongos
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongos
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: mongo
      volumes:
      - name: shared
        emptyDir: {}
      - name: config
        configMap:
          name: vault-agent-config
          items:
            - key: vault-agent-config.hcl
              path: vault-agent-config.hcl
      - name: scripts
        configMap:
          name: cert-scripts
          defaultMode: 0744
      - name: vault-token
        emptyDir:
          medium: Memory
      initContainers:
      - name: mongos-vault-agent
        image: "vault"
        volumeMounts:
        - name: config
          mountPath: /etc/vault
        - name: vault-token
          mountPath: /home/vault
        args:
        - "agent"
        - "-config=/etc/vault/vault-agent-config.hcl"
        env:
        - name: VAULT_ADDR
          value: 'http://vault'
      # since init containers run in order, when the previous exits
      # the vault token will be created at /home/vault/.vault-token
      - name: cert-generator
        image: "vault"
        volumeMounts:
        - name: vault-token
          mountPath: /home/vault
        - name: shared
          mountPath: /certs
        - name: scripts
          mountPath: /scripts
        command: ["/scripts/wrapper.sh"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: VAULT_ADDR
          value: 'http://vault'
        - name: HOME
          value: /home/vault
        - name: SUBJECT_COMMON_NAME
          value: "$(POD_NAME).$(SERVICE_NAME).$(POD_NAMESPACE).svc.cluster.local"
      # Actual container
      containers:
      - name: mongos
        imagePullPolicy: Always
        image: mongo:4.0
        command:
        - mongos
        - '--bind_ip'
        - '0.0.0.0'
        - --configdb
        - "cfg/cfg-0.cfg.default.svc.cluster.local:27019"
        - --maxConns
        - "500"
        - --sslMode
        - requireSSL
        - --clusterAuthMode
        - x509
        # REMOVE THIS AFTER MOVING TO CERT BASED AUTH
        - --sslAllowConnectionsWithoutCertificates
        - --sslPEMKeyFile
        - /certs/mongo/mongodb.pem
        - --sslCAFile
        - /certs/ca/ca.crt
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: shared
          mountPath: /certs
---
kind: Service
apiVersion: v1
metadata:
  # HAS to be equal to the app: XXXX label
  name: mongos
  labels:
    app: mongos
    # Label for the ServiceMonitor to add
    cluster: development
spec:
  selector:
    app: mongos
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
    name: mongo
  - port: 9216
    targetPort: metrics
    name: metrics
  # Headless service
  clusterIP: None
  publishNotReadyAddresses: true


